# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_df=pd.read_csv("Weather_data.csv") #read the weather_data csv file and set to variable
weather_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Moba,33.2288,105.0179,36.140,79,89,1.51,CN,1611897950
1,Yerköy,39.6381,34.4672,29.750,93,83,0.26,TR,1611897954
2,Velizh,55.6056,31.1967,27.230,99,99,1.65,RU,1611897955
3,Oranjemund,-28.5500,16.4333,61.178,80,0,7.28,NaN,1611897956
4,Cidreira,-30.1811,-50.2056,73.328,93,100,7.89,BR,1611897959
...,...,...,...,...,...,...,...,...,...
578,Robertsport,6.7533,-11.3686,78.890,85,1,2.50,LR,1611898426
579,Ladário,-19.0047,-57.6017,73.166,95,100,0.75,BR,1611898427
580,Sagamu,6.8432,3.6478,78.800,94,20,1.40,NG,1611898427
581,Hoquiam,46.9809,-123.8893,37.130,92,5,1.96,US,1611898428
582,Progreso,21.2833,-89.6667,73.400,78,75,3.60,MX,1611898428

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
#configure gmaps

gmaps.configure(api_key=g_key)

In [4]:
#create a figure using gmaps
fig=gmaps.figure()
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
#create a heatmap layer
locations = weather_df[["Lat", "Lng"]].astype(float) #sets the latitude and longitude of each city in the weather_df as the locations for the heatmap
weight= weather_df["Humidity"].astype(float) #sets the city's humidity as the weigh for the heatmap
heat_layer = gmaps.heatmap_layer(locations, weights=weight, 
                                 dissipating=False)

In [6]:
#add the heatmap layer to the existing figure
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
heat_layer.max_intensity =150 #sets the heatmap intensity
heat_layer.point_radius = 3 #sets the radius to increase heat based on city location

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [14]:
#filter the dataframe to only include cities that fit those parameters
#A max temperature lower than 80 degrees but higher than 70.
high_temp=weather_df.loc[(weather_df["Max Temp"]<80) & (weather_df["Max Temp"]>70)] #filter the dataframe to only include cities with a max temp less than 80 and greater than 70

#Wind speed less than 10 mph.
low_speed=high_temp.loc[high_temp["Wind Speed"]<10] #filter the dataframe further to remove cities with a windspeed greater than 10mph

#Zero cloudiness.
hotels_df=low_speed.loc[low_speed["Cloudiness"]==0] #filter the dataframe further to remove the cities with cloudiness above 0%
hotels_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
104,Caravelas,-17.7125,-39.2481,73.922,89,0,1.31,BR,1611898329
109,Tura,25.5198,90.2201,76.676,34,0,1.76,IN,1611898330
143,Sittwe,20.1500,92.9000,76.136,46,0,2.85,MM,1611898336
152,Port Alfred,-33.5906,26.8910,70.826,73,0,5.09,ZA,1611898338
176,Puri,19.8000,85.8500,77.000,50,0,2.57,IN,1611898343
178,Upleta,21.7333,70.2833,78.638,17,0,6.02,IN,1611898344
302,Garoowe,8.4054,48.4845,70.574,47,0,5.57,SO,1611898370
356,Lima,-12.0432,-77.0282,73.994,78,0,4.12,PE,1611898172
383,Conceição da Barra,-18.5933,-39.7322,73.616,89,0,1.11,BR,1611898272
386,Arraial do Cabo,-22.9661,-42.0278,77.000,83,0,4.12,BR,1611898387
389,Lüderitz,-26.6481,15.1594,70.178,49,0,8.71,NaN,1611898387
417,Takoradze,4.8845,-1.7554,77.360,92,0,2.59,GH,1611898393
422,Bhuj,23.2667,69.6667,74.606,19,0,5.43,IN,1611898394
478,Ibrā’,22.6906,58.5334,72.446,24,0,1.06,OM,1611898408

In [15]:
#remove any rows with null values
hotels_df.dropna()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
104,Caravelas,-17.7125,-39.2481,73.922,89,0,1.31,BR,1611898329
109,Tura,25.5198,90.2201,76.676,34,0,1.76,IN,1611898330
143,Sittwe,20.1500,92.9000,76.136,46,0,2.85,MM,1611898336
152,Port Alfred,-33.5906,26.8910,70.826,73,0,5.09,ZA,1611898338
176,Puri,19.8000,85.8500,77.000,50,0,2.57,IN,1611898343
178,Upleta,21.7333,70.2833,78.638,17,0,6.02,IN,1611898344
302,Garoowe,8.4054,48.4845,70.574,47,0,5.57,SO,1611898370
356,Lima,-12.0432,-77.0282,73.994,78,0,4.12,PE,1611898172
383,Conceição da Barra,-18.5933,-39.7322,73.616,89,0,1.11,BR,1611898272
386,Arraial do Cabo,-22.9661,-42.0278,77.000,83,0,4.12,BR,1611898387
417,Takoradze,4.8845,-1.7554,77.360,92,0,2.59,GH,1611898393
422,Bhuj,23.2667,69.6667,74.606,19,0,5.43,IN,1611898394
478,Ibrā’,22.6906,58.5334,72.446,24,0,1.06,OM,1611898408

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [16]:
#insert empty Hotel Name column
hotels_df["Hotel Name"]=""
hotels_df

<ipython-input-16-bae47465b9b1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotels_df["Hotel Name"]=""

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
104,Caravelas,-17.7125,-39.2481,73.922,89,0,1.31,BR,1611898329,
109,Tura,25.5198,90.2201,76.676,34,0,1.76,IN,1611898330,
143,Sittwe,20.1500,92.9000,76.136,46,0,2.85,MM,1611898336,
152,Port Alfred,-33.5906,26.8910,70.826,73,0,5.09,ZA,1611898338,
176,Puri,19.8000,85.8500,77.000,50,0,2.57,IN,1611898343,
178,Upleta,21.7333,70.2833,78.638,17,0,6.02,IN,1611898344,
302,Garoowe,8.4054,48.4845,70.574,47,0,5.57,SO,1611898370,
356,Lima,-12.0432,-77.0282,73.994,78,0,4.12,PE,1611898172,
383,Conceição da Barra,-18.5933,-39.7322,73.616,89,0,1.11,BR,1611898272,
386,Arraial do Cabo,-22.9661,-42.0278,77.000,83,0,4.12,BR,1611898387,
389,Lüderitz,-26.6481,15.1594,70.178,49,0,8.71,NaN,1611898387,
417,Takoradze,4.8845,-1.7554,77.360,92,0,2.59,GH,1611898393,
422,Bhuj,23.2667,69.6667,74.606,19,0,5.43,IN,1611898394,
478,Ibrā’,22.6906,58.5334,72.446,24,0,1.06,OM,1611898408,

In [17]:
#set parameters for finding hotels
params={
    "radius":"5000",
    "type": "lodging",
    "key": g_key
} #create a dictionay of all parameters

In [19]:
#make a api call to get hotels near each city in the df
url="https://maps.googleapis.com/maps/api/place/nearbysearch/json" #set the initial api url equal to variable "url"
count = 0
hotel_found=[]

In [20]:
for index, row in hotels_df.iterrows(): #create a for loop to go through each row fo the hotel_df
    city_name=row["City"] #get the city name as the city variable
    lat_city=row["Lat"] #get the city lat as the lat_city variable
    lng_city=row["Lng"] #get the long as the lng_city variable
    params['location'] = f'{lat_city},{lng_city}' #add the city's lat and lng to the params dictionary as the location
    
    try: #if the api pulls a result for the city
        response=requests.get(url, params=params).json() #request information from the API for the city
        
        results = response["results"] #filter the api response to keep the results dictionary
        print(f'Closest hotel in {city_name} is {results[0]["name"]}') #print the nearest hotel 
        
        hotel_dic={
            "City": city_name,
            "Hotel Name": results[0]["name"]
        } #create a dictionary with the city and hotel name
        
        hotel_found.append(hotel_dic) #add the hotel and city to the empty hotel_found list
        
    except: #if the api doesn't pull a result
        print("No hotel found")
        
    count+=1

Closest hotel in Caravelas is Pousada dos Navegantes
Closest hotel in Tura is Hotel RIKMAN Continental
Closest hotel in Sittwe is Hotel Memory
Closest hotel in Port Alfred is The Halyards Hotel
Closest hotel in Puri is OYO 1577 Hotel Shree Hari Grand
Closest hotel in Upleta is Salman odiya homes
Closest hotel in Garoowe is Curubo Hotel
Closest hotel in Lima is Gran Hotel Bolivar Lima
Closest hotel in Conceição da Barra is Cricaré Praia Hotel
Closest hotel in Arraial do Cabo is Pousada Porto Praia
Closest hotel in Lüderitz is LÜDERITZ NEST HOTEL
Closest hotel in Takoradze is Raybow International Hotel
Closest hotel in Bhuj is Regenta Resort Bhuj
Closest hotel in Ibrā’ is مزرعة راحة النفوس المنزفة

In [21]:
hotel_found

[{'City': 'Caravelas', 'Hotel Name': 'Pousada dos Navegantes'},
 {'City': 'Tura', 'Hotel Name': 'Hotel RIKMAN Continental'},
 {'City': 'Sittwe', 'Hotel Name': 'Hotel Memory'},
 {'City': 'Port Alfred', 'Hotel Name': 'The Halyards Hotel'},
 {'City': 'Puri', 'Hotel Name': 'OYO 1577 Hotel Shree Hari Grand'},
 {'City': 'Upleta', 'Hotel Name': 'Salman odiya homes'},
 {'City': 'Garoowe', 'Hotel Name': 'Curubo Hotel'},
 {'City': 'Lima', 'Hotel Name': 'Gran Hotel Bolivar Lima'},
 {'City': 'Conceição da Barra', 'Hotel Name': 'Cricaré Praia Hotel'},
 {'City': 'Arraial do Cabo', 'Hotel Name': 'Pousada Porto Praia'},
 {'City': 'Lüderitz', 'Hotel Name': 'LÜDERITZ NEST HOTEL'},
 {'City': 'Takoradze', 'Hotel Name': 'Raybow International Hotel'},
 {'City': 'Bhuj', 'Hotel Name': 'Regenta Resort Bhuj'},
 {'City': 'Ibrā’', 'Hotel Name': 'مزرعة راحة النفوس المنزفة'}]

In [36]:
#add the hotel_found list to the dataframe
results_df=pd.DataFrame(hotel_found) #create a dataframe for the hotel_found list

merge_df=pd.merge(hotels_df, results_df, how="left", on="City") #merge the dataframes together
correct_df=merge_df.drop(["Hotel Name_x"], axis=1) #drop the empty hotel name column
hotel_df=correct_df.rename(columns={"City":"City", "Lat":"Lat", "Lng":"Lng", "Max Temp": "Max Temp", "Humidity":"Humidity", "Cloudiness":"Cloudiness", "Wind Speed": "Wind Speed", "Country":"Country", "Date": "Date", "Hotel Name_y":"Hotel Name"}) #rename the columns

hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,Caravelas,-17.7125,-39.2481,73.922,89,0,1.31,BR,1611898329,Pousada dos Navegantes
1,Tura,25.5198,90.2201,76.676,34,0,1.76,IN,1611898330,Hotel RIKMAN Continental
2,Sittwe,20.1500,92.9000,76.136,46,0,2.85,MM,1611898336,Hotel Memory
3,Port Alfred,-33.5906,26.8910,70.826,73,0,5.09,ZA,1611898338,The Halyards Hotel
4,Puri,19.8000,85.8500,77.000,50,0,2.57,IN,1611898343,OYO 1577 Hotel Shree Hari Grand
5,Upleta,21.7333,70.2833,78.638,17,0,6.02,IN,1611898344,Salman odiya homes
6,Garoowe,8.4054,48.4845,70.574,47,0,5.57,SO,1611898370,Curubo Hotel
7,Lima,-12.0432,-77.0282,73.994,78,0,4.12,PE,1611898172,Gran Hotel Bolivar Lima
8,Conceição da Barra,-18.5933,-39.7322,73.616,89,0,1.11,BR,1611898272,Cricaré Praia Hotel
9,Arraial do Cabo,-22.9661,-42.0278,77.000,83,0,4.12,BR,1611898387,Pousada Porto Praia
10,Lüderitz,-26.6481,15.1594,70.178,49,0,8.71,NaN,1611898387,LÜDERITZ NEST HOTEL
11,Takoradze,4.8845,-1.7554,77.360,92,0,2.59,GH,1611898393,Raybow International Hotel
12,Bhuj,23.2667,69.6667,74.606,19,0,5.43,IN,1611898394,Regenta Resort Bhuj
13,Ibrā’,22.6906,58.5334,72.446,24,0,1.06,OM,1611898408,مزرعة راحة النفوس المنزفة

In [39]:
#STUD test the api call to ensure it brings the correct information
caravelas_params={
    "location": "-17.7125, -39.2481",
    "radius": "5000",
    "type": "lodging",
    "key": g_key
} #create a dictionary for the stud city Caravelas

stud_response=requests.get(url, params=caravelas_params).json() #request information from the API for the stud hotel

print(stud_response)

{'html_attributions': [], 'results': [{'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': -17.7379707, 'lng': -39.2589096}, 'viewport': {'northeast': {'lat': -17.7365489197085, 'lng': -39.25753821970849}, 'southwest': {'lat': -17.7392468802915, 'lng': -39.26023618029149}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Pousada dos Navegantes', 'photos': [{'height': 3120, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115337423791997491388">Welison Paiva</a>'], 'photo_reference': 'ATtYBwJBLBoshv7mieL7W66RVH1-6J7ysXfjI5WuVHcMJBprypzV6AZEzL8w5KTHJWJhqRhYIRF1TnhxDUcf5vWusiZ8JVKD5s1DrgODtfPfNf8CK-4tklbRezqUhAsduYPlif0jxIdYk9XCxfJyYsifjWLyvOU8eJigffopN7cDPe27IuuT', 'width': 4160}], 'place_id': 'ChIJVVgc5WnXNAcRLGgmGSFNxr0', 'plus_code': {'compound_code': '7P6R+RC Caravelas, BA, Brazil', 'global_code': '59J27P6R+RC'}, 'rating': 3.5, 'reference': 'ChIJVVgc5WnXNAcRLGgmGSFNxr0', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 138, 'vicinity': 'Rua das Palmeiras, 45, Caravelas'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': -17.7347306, 'lng': -39.2653284}, 'viewport': {'northeast': {'lat': -17.7334292197085, 'lng': -39.2640352197085}, 'southwest': {'lat': -17.7361271802915, 'lng': -39.2667331802915}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Pousada Tropical', 'photos': [{'height': 2592, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115140552705841837617">Hercules Oliveira</a>'], 'photo_reference': 'ATtYBwJlmtur4Xc73YKvwgcO98s6Tvd8fYY7HWlmOB5py7kb0upxGFB5lhw1GPZL53ASLckLwYpvL5Zn04M6mcFK0xTRIQBOvhitfMGQmLtRcW0c-wKb3urj4JYrRzL80AvsLwiL1_BQZxh_VXP8doMyG2GWSPTbj2tYYDamwcc6C0Y1Z7Hy', 'width': 1944}], 'place_id': 'ChIJ51eRJe7ZNAcRoL0JWIePd1Y', 'plus_code': {'compound_code': '7P8M+4V Caravelas, BA, Brazil', 'global_code': '59J27P8M+4V'}, 'rating': 4.3, 'reference': 'ChIJ51eRJe7ZNAcRoL0JWIePd1Y', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 6, 'vicinity': 'Rua Sete de Setembro, 155, Caravelas'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': -17.7380161, 'lng': -39.25800020000001}, 'viewport': {'northeast': {'lat': -17.7366947697085, 'lng': -39.2566600197085}, 'southwest': {'lat': -17.7393927302915, 'lng': -39.2593579802915}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Pousada Encanto Abrolhos', 'photos': [{'height': 2322, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105706485672688623006">Edriano Souza Guia de Ecoturismo</a>'], 'photo_reference': 'ATtYBwKpIOF7H5wuX5_PlaSGxnDwzSPlpMt-HNvycIoXPrM2ZgzRJF6LmOal4dtwPD90l43i0o5i_XoZIcothfHiIA4pagDGh2YIz2eqY450b7-uN8_NiGATJgldMFUAlDOJrFWpVFdXTg4JWY8M4nMGjZScWHhPYvPyye0LGdkdTdG7KpWy', 'width': 4128}], 'place_id': 'ChIJ51eRJe7ZNAcRELF7pdeMsdw', 'plus_code': {'compound_code': '7P6R+QQ Caravelas, BA, Brazil', 'global_code': '59J27P6R+QQ'}, 'rating': 3.6, 'reference': 'ChIJ51eRJe7ZNAcRELF7pdeMsdw', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 75, 'vicinity': 'Avenida Ministro Adalício Nogueira 115, Caravelas'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': -17.7352169, 'lng': -39.2649789}, 'viewport': {'northeast': {'lat': -17.7338838197085, 'lng': -39.2636475197085}, 'southwest': {'lat': -17.73658178029151, 'lng': -39.2663454802915}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Pousada do Beco Shangri-La', 'photos': [{'height': 2340, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116254233089608536311">Eduardo Segatto</a>'], 'photo_reference': 'ATtYBwIKOZNYsVYsQzLSwmiWXo_fitSuLncYyet0EyvW9BgoqzeqLrA-7zyLztyDRGhWlNKdV8HmW6Sp2lCb45b18NtQNsOiojebvZtpGcGgN8FLoW-_e_SJHN0v1ildUTtrS5AvtolDpY-I4YbKGSTm4IjC9utjcKOsdfDatV_0dwYA7peV', 'width': 4160}], 'place_id': 'ChIJ51eRJe7ZNAcRj1k7zDN9mPs', 'plus_code': {'compound_code': '7P7P+W2 Caravelas, BA, Brazil', 'global_code': '59J27P7P+W2'}, 'rating': 3.9, 'reference': 'ChIJ51eRJe7ZNAcRj1k7zDN9mPs', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 53, 'vicinity': 'Rua Sete de Setembro, 219, Caravelas'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': -17.736329, 'lng': -39.26453800000001}, 'viewport': {'northeast': {'lat': -17.7349831197085, 'lng': -39.2631925697085}, 'southwest': {'lat': -17.7376810802915, 'lng': -39.2658905302915}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Sadine r cardoso', 'photos': [{'height': 3000, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115852380802147316451">Sadine rodrigues Cardoso</a>'], 'photo_reference': 'ATtYBwLPsM3lcc-kEux3-Nxv1_AbVGM2CdoNbsRprYsg2q6sxO4Muvm6-QvWgdfNwEgr3ZjRFnKc1oe6UGFIyhAnNaxm_cDMhUlyOaO2NhAkZFWqCNqrztix01koNqxzJgbCaCwbXXgQWumETAu2DnF_6TRSgX__-GrjkQomENHMhzbjYAHz', 'width': 4000}], 'place_id': 'ChIJ91o-_FTXNAcRzx2ofiPjcrA', 'plus_code': {'compound_code': '7P7P+F5 Caravelas, BA, Brazil', 'global_code': '59J27P7P+F5'}, 'rating': 5, 'reference': 'ChIJ91o-_FTXNAcRzx2ofiPjcrA', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'Rua Aníbal Benévolo, 415 - Centro, Caravelas'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': -17.7410855, 'lng': -39.2459705}, 'viewport': {'northeast': {'lat': -17.7397905697085, 'lng': -39.2443831197085}, 'southwest': {'lat': -17.7424885302915, 'lng': -39.2470810802915}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Pousada Liberdade', 'photos': [{'height': 3456, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107059790399652216887">Amd Dietz</a>'], 'photo_reference': 'ATtYBwI44Gb9cwMs7cl4AZd0NsNnklmfPv01MWnRuKO-yttw6aV6bCzGRJyiWuLpZqV_BuXLHHSEOWsb2MJFFrQKnc90Dmo55l8GLw3mwCAAOLBN05DZhjk7IG1G8Uau5BwplFoULuvXV4j3EFgmE7eiuMC2ZBcWrTGwum4NxPOheALtyjkB', 'width': 4608}], 'place_id': 'ChIJXcW1LU_XNAcRG4x6mdMStYg', 'plus_code': {'compound_code': '7Q53+HJ Caravelas, BA, Brazil', 'global_code': '59J27Q53+HJ'}, 'rating': 4.3, 'reference': 'ChIJXcW1LU_XNAcRG4x6mdMStYg', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 128, 'vicinity': 'Av. Ministro Adalício Nogueira, 1551 - Tancredo Neves, Caravelas'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': -17.7431944, 'lng': -39.24093329999999}, 'viewport': {'northeast': {'lat': -17.7418121197085, 'lng': -39.2395732697085}, 'southwest': {'lat': -17.74451008029151, 'lng': -39.24227123029149}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png', 'name': 'Mar Doce de Abrolhos', 'opening_hours': {'open_now': False}, 'photos': [{'height': 2012, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102086221268556117419">Mar Doce de Abrolhos</a>'], 'photo_reference': 'ATtYBwKcpjBMQaa2EypmAy6tNZcgeQweE8OzVioYDzuqKq0_GEf4L8uz2DjPWfRg1CqHwbrIp2Ss9M7EYEJpY4yZiwfeMrFIPg1Ya7GkuZ4EK-qJ_7g-1CpyVMY8VQqId-MM8kfmDl0Eu92fZcoESSMo-4iTwWFFp7BE-PLTDLbt_iNzQZxv', 'width': 1965}], 'place_id': 'ChIJI1JMq0vXNAcRmKk8FltpJM0', 'plus_code': {'compound_code': '7Q45+PJ Caravelas, BA, Brazil', 'global_code': '59J27Q45+PJ'}, 'rating': 4.8, 'reference': 'ChIJI1JMq0vXNAcRmKk8FltpJM0', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 16, 'vicinity': 'Estrada para Barra de Caravelas, 1632, Caravelas'}], 'status': 'OK'}

In [43]:
#STUD part 2 print the results from the api call
results = stud_response["results"] #filter the api response to keep the results dictionary
results
print(f'Closest hotel is {results[0]["name"]}') #print the nearest hotel

Closest hotel is Pousada dos Navegantes

In [37]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [39]:
# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info) #create a marker layer to find the hotels

fig.add_layer(marker_layer) #add the marker layer to the figure

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))